FROM node:14

WORKDIR /app

COPY ./dist .

RUN npm ci --only=prod

ARG NODE_ENV=production

ARG DIST_DIR='..'

ARG PORT=8080

ARG LOG_FORMAT=console

ARG MONGO_DB_CONNECTION=''

ARG EMAIL_SENDGRID_API_KEY=''

ARG EMAIL_SENDER_ADDRESS=''

ENV NODE_ENV=${NODE_ENV} \
    DIST_DIR=${DIST_DIR} \
    PORT=${PORT} \
    LOG_FORMAT=${LOG_FORMAT} \
    MONGO_DB_CONNECTION=${MONGO_DB_CONNECTION} \
    EMAIL_SENDGRID_API_KEY=${EMAIL_SENDGRID_API_KEY} \
    EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}


RUN echo "Vars: ${PORT} ${NODE_ENV} ${LOG_FORMAT}"

RUN npm -v

RUN node -v

EXPOSE ${PORT}

CMD ["npm", "start"]
